print("hello world")
print("john")
print("john kennedy")
print("hi, i am python.")
print(25)
print(2*2)
print("2+5+9")
print("hello,","i","am","john.")
print("john","is",20,"years","old.")
print(5,"+",4,"=",5+4)